Waterlogged/Models/Calendar/WorkoutEntry.cs
using System;
using System.Collections.Generic;

namespace Waterlogged.Models
{
    public class WorkoutEntry
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime? DateCreated { get; set; }
        public IList<DetailsSet> WorkoutSets { get; set; }
    }
}

Waterlogged/Controllers/CalendarController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Waterlogged.BLL.Interfaces;
using Waterlogged.Data;
using Waterlogged.Data.Models;
using Waterlogged.Models;
using Waterlogged.ViewModelHelpers;

namespace Waterlogged.Controllers
{
    public class CalendarController : BaseController
    {
        private WaterloggedDbContext _db;
        private IWorkoutLogic _workoutLogic;
        private IMapper _mapper;
        private WorkoutSetHelper _workoutSetHelper;

        public CalendarController(WaterloggedDbContext db, IWorkoutLogic workoutLogic, IMapper mapper, WorkoutSetHelper workoutSetHelper) : base(mapper)
        {
            _db = db;
            _db.SetUserId(UserId);
            _workoutLogic = workoutLogic;
            _workoutSetHelper = workoutSetHelper;
            _mapper = mapper;
        }

        // GET: Calendar
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetWorkouts()
        {
            var workouts = _mapper.Map<List<Workout>, List<EditWorkout>>(_db.Workouts.ToList());
            return new JsonResult { Data = workouts, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        [HttpPost]
        public JsonResult SaveWorkout(EditWorkout workout)
        {
            bool status = false;
            if (!ModelState.IsValid)
            {
                return new JsonResult { Data = new { status = status } };
            }

            int workoutId = workout.Id;
            if (workout.Id > 0)
            {
                var workoutToModify = _db.Workouts.Find(workout.Id);
                _workoutLogic.EditWorkout(workout, workoutToModify);
                status = true;
            }
            else
            {
                workoutId = _workoutLogic.CreateWorkout(workout);
                status = true;
            }
            return new JsonResult { Data = new { status = status, workoutId = workoutId } };
        }

        [HttpPost]
        public JsonResult DeleteWorkout(int workoutId)
        {
            var status = false;
            var workoutToRemove = _db.Workouts.FirstOrDefault(x => x.Id == workoutId);
            if (workoutToRemove != null)
            {
                _db.Workouts.Remove(workoutToRemove);
                _db.SaveChanges();
                status = true;
            }
            return new JsonResult { Data = new { status = status } };
        }

        public ActionResult EditWorkout(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Workout workout = _db.Workouts.Find(id);
            if (workout == null)
            {
                return new HttpNotFoundResult();
            }

            var editWorkout = _mapper.Map<EditWorkout>(workout);
            foreach (var set in editWorkout.WorkoutSets)
            {
                set.DistanceUnits = _workoutSetHelper.DistanceUnitsSelectList;
                set.RestTypes = _workoutSetHelper.RestTypesSelectList;
                set.StrokeTypes = _workoutSetHelper.StrokeTypesSelectList;
            }

            return View("CalEditWorkout", editWorkout);
        }

        public ActionResult AddWorkout(DateTime? start, DateTime? end)
        {
            if (!start.HasValue)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var editWorkout = new EditWorkout { StartDate = start.Value };
            foreach (var set in editWorkout.WorkoutSets)
            {
                set.DistanceUnits = _workoutSetHelper.DistanceUnitsSelectList;
                set.RestTypes = _workoutSetHelper.RestTypesSelectList;
                set.StrokeTypes = _workoutSetHelper.StrokeTypesSelectList;
            }

            return View("CalEditWorkout", editWorkout);
        }

        public ActionResult WorkoutDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Workout workout = _db.Workouts.Find(id);
            if (workout == null)
            {
                return new HttpNotFoundResult();
            }

            var editWorkout = _mapper.Map<DetailsWorkout>(workout);
            return View("CalWorkoutDetails", editWorkout);
        }
    }
}

Waterlogged/Views/Calendar/CalEditWorkout.cshtml
@model Waterlogged.Models.EditWorkout

@{
    Layout = null;
    ViewBag.Title = "Edit Workout";
}
@using (Ajax.BeginForm("SaveWorkout", "Calendar", null, new AjaxOptions() { OnSuccess = "WorkoutSaved(data)" }, null))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.EditorForModel()

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input id="saveWorkoutBtn" type="submit" value="Save" class="btn btn-default pull-right" />
            </div>
        </div>
    </div>
}

@section Scripts
{
}

Waterlogged/Views/Calendar/CalWorkoutDetails.cshtml
@model Waterlogged.Models.DetailsWorkout
@{
    Layout = null;
}

<div>
    <h4>Workout</h4>
    @Html.CustomHR()
    @Html.DisplayForModel()
</div>

<h4>Sets</h4>
@Html.CustomHR()
@Html.DisplayFor(x => x.WorkoutSets)

Waterlogged/Views/Calendar/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div id="calendar" style="margin-top: 20px;"></div>

<div id="workoutModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"><span id="workoutName"></span></h4>
            </div>
            <div class="modal-body">
                <button id="btnDelete" class="btn btn-default btn-small pull-right">
                    <span>Remove</span>
                </button>

                <button id="btnEdit" class="btn btn-default btn-small pull-right">
                    <span>Edit</span>
                </button>

                <div id="workoutDetails"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<div id="saveWorkoutModal" class="modal fade" role="dialog">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"><span id="saveTitle">Save Workout</span></h4>
            </div>
            <div class="modal-body">
                <div id="editWorkoutContainer">
                    <!--Views/Shared/EditorTemplates/EditWorkout.cshtml is inserted here-->
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

                <button type="button" class="hidden" id="workoutSavedBtn"></button>
            </div>
        </div>
    </div>
</div>

<link href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.7.0/fullcalendar.min.css" rel="stylesheet" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.7.0/fullcalendar.print.css" rel="stylesheet" media="print"/>
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css" rel="stylesheet" />

@section Scripts 
{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.7.0/fullcalendar.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>

    @Scripts.Render("~/bundles/jqueryUnobtrusiveAjax")
    <script src="~/Scripts/Waterlogged/Calendar/CalendarIndex.js"></script>
}